### PR TITLE
new sexy color scheme + layout issue fix

### PR DESCRIPTION
**Pull request by CaptainChloride**
Halo!

I've added a new color scheme almost everyone likes so if you don't then you're not human. pls merge oke? :smile:

### CODE REVIEW

**Comment by amandagrice** [comment]
Thanks mate :)

**Comment by CaptainChloride** [comment]
Oh jolly me! Why I aim simply to please. Its quite satisfying to see that
you enjoy the beau color scheme m'lady. Do have a nice day *a very British
bow ensues*

**Comment by amandagrice** [comment]
Pffft :p

**Comment by CaptainChloride** [comment]
That's not a very British thing to say. They would most likely throw hot tea on you :tea:

**Pull request merged**
